### ISSUE TITLE
"--no-run" flag not working (via pre-commit)

### ISSUE THREAD

**Issue by jamesmyatt** [christopher-hacker/enforce-notebook-run-order#14]
I want to disable running the notebooks as part of the pre-commit hook since it takes far too much time. However, the following doesn't config seem to work.

```
  - repo: https://github.com/christopher-hacker/enforce-notebook-run-order
    rev: 1.4.1
    hooks:
      - id: enforce-notebook-run-order
        args: ["--no-run"]
```

The logs contain the following messages, so it looks like the "no-run" flag is being recognised but it's still trying to run the notebook. Is that correct?

```
<user>\.cache\pre-commit\repoy8lvwlom\py_env-python3\Lib\site-packages\enforce_notebook_run_order\cli.py:29: UserWarning: The --no-run option will not catch all problems with notebooks. It is possible that the checks will pass, but the notebook was still run out of order. It is highly recommended to move any long-running code to a separate task that runs separately from the notebook.
  warnings.warn(
Traceback (most recent call last):
  File "<...>\.cache\pre-commit\repoy8lvwlom\py_env-python3\Lib\site-packages\enforce_notebook_run_order\enforce_notebook_run_order.py", line 86, in check_single_notebook
    temp_nb.check_notebook()
  File "<...>\.cache\pre-commit\repoy8lvwlom\py_env-python3\Lib\site-packages\enforce_notebook_run_order\temp_notebook.py", line 112, in check_notebook
    output_data = self.run()
                  ^^^^^^^^^^
  File "<...>\.cache\pre-commit\repoy8lvwlom\py_env-python3\Lib\site-packages\enforce_notebook_run_order\temp_notebook.py", line 66, in run
    raise NotebookRunFailedError(
enforce_notebook_run_order.temp_notebook.NotebookRunFailedError: Notebook <...>\Temp\tmp7m1kj2jb\temp_notebook.ipynb failed to run.
```

**Comment by jamesmyatt** [comment]
To be honest, when running via pre-commit, in order to run the notebooks you'd have to inject all of the dependencies into the pre-commit environment, which isn't practical, or you'd have to run it locally, in which case it won't use the hook config from this repo anyway. Hence, I think that --no-run should be the default for the pre-commit hook here.

So, IMO, this tool currently doesn't work as a pre-commit hook.

**Comment by jamesmyatt** [comment]
@christopher-hacker , I'll open a new issue to discuss whether "No run" should be the default for the pre-commit hook.
